### PR TITLE
Registered angular-jwt interceptor for X-Access-Token

### PR DESCRIPTION
**Pull request by tombee**
@ehazlett 
I was having a look to see if we can improve the authentication on the UI in some way.  I thought it'd be good to introduce an interceptor that fires whenever `$http` is called and includes our token.

When doing some research on how folks are doing this in the AngularJS world, JSON Web Tokens (JWT) were recommended.  I've used the `angular-jwt` package anyway, but tweaked it to add the header in the `X-Access-Token` format the Shipyard is currently familiar with.  Perhaps support for JWT on the server side would be handy, as that's token authentication stuff that we can re-use.. and there's a go package for it already.

JWT might also give us the ability to better support user/role based actions, as we can store the username, role and an expiry in the token that the UI can decode and make decisions based upon.

Let me know what you think on this. :smile:

### CODE REVIEW

**Comment by tombee** [comment]
Oh yeah -- and I'd say this is just a baby-step in the refactoring of the auth stuff that we have. :yum:

**Comment by ehazlett** [comment]
Nice!  I like the idea of this.  I will test this and take a look at the Go JWT package as well.

**Comment by ehazlett** [comment]
is this still valid for v3?

**Comment by tombee** [comment]
This work has been moved to V3.

**Pull request closed without merging**
