### PR TITLE
Registry v2

### PR DESCRIPTION
**Pull request by computerlyrik**
- adds controller gluecode for @ehazlett registry-client-api
- fixes some view fields
- merges with current master

refs https://github.com/shipyard/shipyard/issues/625

### CODE REVIEW

**Comment by clhlc** [comment]
now ，we can add registry v2?

no i try it ,only support v1 (upgrade my shipyard-controller)

**Comment by ehazlett** [comment]
Thanks for the contribution.  I'll get it reviewed :)

**Comment by clhlc** [comment]
I clone registry-v2 branch, and docker-compose up, but not support  v2?

it's  also .../v1/search...

**Comment by nfoonf** [comment]
still seems to call only v1-api.

**Comment by soninob** [comment]
We have a PR submitted for supporting V2, please check #852

**Comment by soninob** [comment]
I think this one can be close, #852 has been merged.

**Comment by tombee** [comment]
@ehazlett 
Think we can close this as per @soninob's comment.

**Pull request closed without merging**
