### PR TITLE
Whats a top command without a terminal? Lets try a CSS one!

### PR DESCRIPTION
**Pull request by robtec**
Could be a crazy move on my part... :laughing:

### CODE REVIEW

**Comment by robtec** [comment]
I can change the colours and stuff to make it like the V3 theme, just pitching the initial idea/concept :smile:

**Comment by tombee** [comment]
Could we get a screenshot?

**Comment by robtec** [comment]
screen shot 2015-04-12 at 17 12 21

The font looks a little different in the picture :laughing:

**Comment by tombee** [comment]
Heh, cool terminal.. but I don't think it fits here for this table.  Can probably re-use some of the stuff you've learnt from this on container websocket attach work that needs to be done.  What do you think?

**Comment by ehazlett** [comment]
I agree with @tombee -- this looks beautiful but i think i prefer the table in this place.  I have been playing with the websocket stuff this weekend -- this could fit there :)  Thanks!

**Comment by robtec** [comment]
Cool 😊

**Pull request closed without merging**
