### PR TITLE
Added Swarm Constraints to deploy page

### PR DESCRIPTION
**Pull request by robtec**
Just a mock up for now, need to get it sent to the Swarm Master next :)

### CODE REVIEW

**Comment by robtec** [comment]
screen shot 2015-04-22 at 22 53 31

**Comment by ehazlett** [comment]
Nice!  Could we span the same number of columns as the above?

**Comment by robtec** [comment]
@ehazlett better?

screen shot 2015-04-22 at 23 00 30

**Comment by ehazlett** [comment]
Nice. Yep. I like that better :). Thx!

**Comment by robtec** [comment]
screen shot 2015-05-02 at 15 08 22

@tombee nice one man :+1:

**Comment by tombee** [comment]
Awesome @robtec  -- error interceptor for the wins!

Nice work :+1:

**Pull request merged**
