### PR TITLE
Ability to start privileged containers

### PR DESCRIPTION
**Pull request by tombee**
Fix for Issue #309:
Depends upon https://github.com/citadel/citadel/pull/91

### CODE REVIEW

**Comment by tombee** [comment]
Think these tests were failing already?

**Comment by ehazlett** [comment]
@tombee since this is merged in citadel, you will want to update Godeps with the latest rev.

**Comment by tombee** [comment]
Thanks @ehazlett, now referencing https://github.com/citadel/citadel/commit/5104bb4b9f2d05f97f852c870d82aae9621084c2

**Comment by ehazlett** [comment]
That specific error was from not being able to find that revision in
citadel -- it was probably your local fork.

**Pull request closed without merging**
