### PR TITLE
added DNS support

### PR DESCRIPTION
**Pull request by rustjson**
For issues https://github.com/shipyard/shipyard/issues/624

### CODE REVIEW

**Comment by tombee** [comment]
LGTM!

Not sure if we want to also add something into our container inspect page to show the DNS settings, since we're able to set them via the deploy page now?

**Comment by rustjson** [comment]
Hum, Let me add it now.

**Comment by rustjson** [comment]
@tombee, Done, But this will only show user defined DNS settings. default DNS will not show here. Show we read the resolv.conf to make it better?

**Comment by tombee** [comment]
Maybe just hide the DNS field if a custom DNS isn't provided, unless you know of an easy way of reading the resolv.conf for a remote machine?

**Comment by rustjson** [comment]
Well, currently has no idea, will try handle it tomorrow.

**Comment by tombee** [comment]
Okay, for now let's keep this PR simple and only display the DNS
information returned from the API. We can hide the DNS section on the
inspect page if it's empty. Sound reasonable?

**Comment by rustjson** [comment]
@tombee  Finished

**Comment by tombee** [comment]
Cool, thanks!  I was just running this but the DNS section on the inspect page doesn't seem to be populated for me.  Is it definitely working okay for you?

**Comment by tombee** [comment]
LGTM!

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
