### PR TITLE
[WIP] New UI for 1.12

### PR DESCRIPTION
**Pull request by tombee**
This is the beginning of developing a new UI for Shipyard that is Docker 1.12 compatible.  The new UI will be using React instead of Angular.

The UI is currently limping along, the user is able to log in and list containers.  With a few backend tweaks we should be able to get the rest of the UI to display services, tasks, containers, images, nodes, volumes, networks.

I think there are few remaining items for this PR before merging:
- [x] Route APIs to engine instead of swarm
- [x] Ensure all APIs that require credentials are given the authorization header and token

Once we have these items, we should have a functional (but limited) UI.

### CODE REVIEW

**Comment by ehazlett** [comment]
This is awesome!  I'll take a look and give it a spin :fireworks:

**Comment by tombee** [comment]
Here are some early screenshots of the progress so far:



2016-06-25-02-00-31_1392x950

2016-06-25-02-00-20_1864x797

2016-06-25-02-00-08_1855x673

2016-06-25-01-59-53_1855x839

**Comment by tombee** [comment]
Made a few more modifications, it now works and I just successfully created a service using shipyard!

2016-06-29-23-48-02_1635x868
2016-06-29-23-42-47_1974x803

**Comment by tombee** [comment]
Still lots to do, but this should provide basic login/logout functionality along with being able to browse the various swarm mode resources.  You're also able to create a basic service and volume.

Needs some time now mapping the API requests/responses for the various pages now most of the routes are in place.

Help on this would be welcome!

unclesam

**Comment by tronicum** [comment]
Will the legacy swarm support still stay?

**Comment by tombee** [comment]
@tronicum: I'll defer to @ehazlett on the overall plans for 1.12.  Just hacking in my spare time to get a new UI together that supports the new service constructs etc. :smile:

**Comment by ehazlett** [comment]
@tronicum shipyard tries to stay on par with the latest docker release.  i'm not sure if we have the resources to support both legacy swarm and new swarm mode but I'm not opposed to contributions.

@tombee @lyndaoleary  thanks for all of the hard work!

**Comment by ehazlett** [comment]
@tombee after thinking about this some i think we should allow non swarm mode as well.  maybe an option to skip the "Initialize" or move the Initialize to the Service view to activate later.  That way we can still manage containers, etc. without having to enable it if not needed.

thoughts?

**Comment by tombee** [comment]
@ehazlett @tronicum 
Personally I think it'd be great if we could support both, I think it's more a matter of time and resources than anything.  My worry with the 1.12 work is that there's quite a bit of work we need to do already to support swarm mode without bringing all of the legacy that comes with non-swarm mode.  

The other concern is that I'm not sure how 'compatible' the two modes will be with each other.  Deployment of swarm mode and non-swarm mode might be quite different, and the feature sets they will support might be quite different too.

For the moment I'd like to concentrate on getting a robust and clean swarm mode solution in place.  We can see where to go from there, depending on what time/resources we have available at the time.

**Comment by markrey** [comment]
Any specific reason it doesnt work on Mac. When i go to http://192.168.99.100:8080/ it shows blank.

screen shot 2016-07-15 at 4 09 52 pm

**Comment by tombee** [comment]
@markrey Could you try using Docker for Mac? The development setup needs
access to the code mounted as a volume and inotify events for watching for
changes.

I can't tell exactly what's gone wrong there from this error, but the 404
on the /swarm API suggests there might have been an issue setting up the
proxy/backend on docker-machine.

**Comment by ehazlett** [comment]
lgtm so far.  I'm going to merge this so we can start working on the branch instead of this PR.

Thanks!

**Comment by tombee** [comment]
Woohooo 🎉

**Comment by thaJeztah** [comment]
Awesome!

**Comment by tombee** [comment]
Thanks @thaJeztah! :smile:

**Comment by faddat** [comment]
@tombee thanks for your work on this!

I'll be testing today, if there's anything you'd like me to poke at in particular,  feel free to let me know.  Also, I think that only supporting Swarm Mode vs Swarm Mode + Swarm was the right call -- if 2 years in dockerland has taught me anything, it's that one should stick with the mothership or be abandoned :).

**Comment by jmzwcn** [comment]
Old release support swarm and new release support swarm mode. I think user could choose by themselves.

**Comment by fitz123** [comment]
Greetings, Guys!

2nd day with Docker, new swarm mode rocks! It's awesome you support it so fast. My question regarding installation part for 1.12 version for a newbie. Is there any way to get new shipyard container? Could you probably push it into docker hub?
I have no Go or NodeJS knowledge and only 2nd day testing docker. So there no way I'll be able to compile all stuff from repo manually in near future. 
I've tried to use docker-compose with 1.12 branch, but getting an 'old' version with Swarm container
Maybe you have a timeline for documentation for the new version?

Thank you again for incredible work!

**Comment by faddat** [comment]
@fitz123
Similar difficulty here.  Maybe try making a .dsb bundle with compose?

I am not sure I tried that yet or not...

**Comment by fitz123** [comment]
Just managed to install it =) My issue was checkout into _origin/1.12_ branch instead of _1.12_
For those who're struggling like me with installation, you need to do 4 steps to get it work:
1. `git clone https://github.com/shipyard/shipyard.git && cd shipyard`
2. `git checkout 1.12`
3. `docker-compose build`
4. `docker-compose up`
And it works!

**Comment by michelvocks** [comment]
@tombee @ehazlett 
Great work so far. I would really love to contribute. Is there any "starting point" where I could get my hands on?

**Comment by borzamircea** [comment]
@tombee @ehazlett 

Looking great so far. Managed to clone and play with the code for a bit. Is htere any reason why the registries tab is gone? Are you supporting the ability to add a `v1` or `v2` ;) registry anymore or it was not implemented yet for the new UI. Thanks a lot! Cheers!

**Comment by oleksiilopasov** [comment]
Hi @tombee 
Can you provide us with some information about release dates (or release-candidates)?

**Comment by manast** [comment]
Looks really great, and its already a bit useful if you are starting doing stuff in swarm mode. Good job guys!

**Comment by yeruisen** [comment]
Looks really great.

**Comment by jmzwcn** [comment]
Considering k8s dashboard more and more comfortable, where is the road of docker public easy-to-use(not CS version)?

**Comment by agenge** [comment]
@fitz123 I am having problems with this step. details as follows:
1. docker-compose up 
2. log in http://192.168.56.102:8080  
3. go to the "Get Started" page
4. Click the “Initialize” button

but ,No response after clicking. 
the ssh console logs:
`controller_1  | time="2016-11-10T02:50:06Z" level=debug msg="POST: /swarm/init"`

On the “Initialize” page , open chrome F12 console and Refresh, Output 406 error:
`GET http://192.168.56.102:8080/swarm 406 (Not Acceptable)`

Click the “Initialize” button, Output 500 error:
`POST http://192.168.56.102:8080/swarm/init 500 (Internal Server Error)`

How to solve this problem? thanks.

**Comment by faddat** [comment]
Good question Daniel.

I would point at any number of third party tools like crane, but.... This
is a weak point for docker and it's starting to show.  I'm interested to
see a roadmap on this?

Basically, I think that the community wants to have a good looking UI and a
predictable back end for that UI.  DAB != Predictable.  Swarm didn't make
any sense at all after it hit the scene.  I know it's experimental, but
it's effect is clear and undeniable. It threw my conception of multi host
docker cluster straight into the fire. I still don't really get its
relationship to my compose files.

If it helps I consider myself a fairly advanced user of docker, kube, and
rancher and a mid-low gopher.  I want to love swarm mode but sure haven't
been able to bring myself to.

**Comment by manast** [comment]
@faddat swarm mode is one of the best things that have happen in docker since it inception, but surely it is rough in the corners and I had to develop quite a big chunk of tooling for our release process and still it is not 100% perfect...

**Comment by faddat** [comment]
I agree with all of this, and want to note that any complaint is directed
at Docker, Inc.

DAB is still somewhat "what!??"

;)

**Comment by tombee** [comment]
@faddat @manast @agenge @aleksejlopasov @borzamircea 
I'm really sorry for the late response on this! :disappointed: I've had a few things on my plate and just haven't been able to get around to continuing with this work.

Now that things have settled down in the 1.12 API, it should reduce some of the churn I was facing.

I'll re-test soon with the latest version of 1.12 and fix the swarm incompatibility issues folks had mentioned.  I think this is probably because join tokens changed between the RC that I was building this on and the 1.12 release.

@jmzwcn 
Shipyard isn't an official product of Docker, Inc. and its development isn't sponsored by Docker, Inc., so I think this is probably a question that should be directed at the Docker, Inc. forum.  It's not something that I am able to answer, sorry! :smile:

**Comment by stealthybox** [comment]
@tombee no problem!
None of us are entitled to your time -- Thanks for all of your work on this!

I want to get involved. What can I do to help you vet out the integration with swarm features?

I have an existing swarm cluster with Traefik running as the service LB.
I'm starting to understand the relation between the necessary components of shipyard, but when I spun it up with docker-compose, I wasn't able to access the published ports externally from the node (only on localhost).

I started playing around with converting the compose stack to services but haven't succeeded yet.

**Comment by faddat** [comment]
ZOMG.

I had no idea Shipyard wasn't funded by Docker.  

Where might someone send you some bitcoin?

**Comment by tombee** [comment]
@stealthybox 
You're very welcome, it'd be great to have your help on Shipyard!  You're free to help out wherever you feel you are most comfortable contributing.  If you want to discuss ideas/suggestions, feel free to reach out on IRC to @ehazlett or I.  We're regularly on #shipyard on freenode.

@faddat 
That's very kind 😄, but I contribute to shipyard because I enjoy it, so don't worry about it!  You can repay Shipyard contributors by continuing to support us with your help and ideas.

**Comment by tombee** [comment]
@stealthybox @agenge @michelvocks 
I've put a PR up that hopefully gets the branch working again.  I'm assuming any `swarm init` errors were probably due to not specifying a listen address.  So I've added some additional error reporting and a listen address field to get us moving again.

https://github.com/shipyard/shipyard/pull/901

**Comment by javrasya** [comment]
When I hit Craete Service button, nothing happened. I just see an error log in browser console like;

```
TypeError: null is not an object (evaluating 'internalInstance.getHostNode')
```

**Pull request merged**
