### PR TITLE
Moved linking and volumes to center column

### PR DESCRIPTION
**Pull request by robtec**

### CODE REVIEW

**Comment by tombee** [comment]
:+1: I wonder how these would look as 'compact' tables?

**Comment by robtec** [comment]
@tombee looking at that now

**Comment by ehazlett** [comment]
hmm yeah perhaps we can add a default for empty content - it looks a little odd when it's empty:

2015-04-13-185108_1298x287_scrot

**Comment by robtec** [comment]
Hmm how about if nothing exists then hide the title too?

**Comment by robtec** [comment]
Making better use of the space for sure :smile: 

screen shot 2015-04-19 at 03 10 26

screen shot 2015-04-19 at 03 10 46

**Comment by ehazlett** [comment]
Thanks!  Would you mind squashing these commits?

**Comment by robtec** [comment]
I should have done this earlier, cheers dude :smile:

**Comment by robtec** [comment]
Current screenshot :+1: 

screen shot 2015-04-19 at 14 25 27

**Comment by ehazlett** [comment]
LGTM :+1:

**Pull request merged**
