### PR TITLE
Added deploy from image

### PR DESCRIPTION
**Pull request by rustjson**
@tombee  like you said

``` bash
Hmm in JasonYoung's case, we might be able to add a link from the images view to the deploy page, with the image name filled out
```

Done!

### CODE REVIEW

**Comment by tombee** [comment]
I can see the deploy buttons, but when I click them.. it doesn't seem to do anything for me.

Also, an alternative approach might be to use the `ui-sref` directive e.g. `ui-sref="dashboard.deploy({image: 'busybox'})"`

We can then ensure that our deploy route accepts an `image` route parameter.

**Comment by tombee** [comment]
Looks good and seems to work nicely, just wondering if it might be worth tweaking the way the image info is passed, as I'm not sure about passing the image name like so: `http://127.0.0.1:8080/#/deploy/busybox:latest/`.  

An alternative approach might be to use the ui-sref directive e.g. `ui-sref="dashboard.deploy({image: 'busybox'})"`.  We can then ensure that our deploy route accepts an image route parameter.

Any thoughts on this @ehazlett?

**Comment by ehazlett** [comment]
@tombee ya +1.  I'm not crazy about sending via the URL params.  I like the route because we could then use that in a registry view if desired.

**Comment by ehazlett** [comment]
Closing as this has gone stale.  Please re-open a new PR if you want to add this.  Thanks!

**Pull request closed without merging**
