### PR TITLE
LDAP BaseDN improvements

### PR DESCRIPTION
**Pull request by meister**
Disregard branch name, originally idea was a bit different..

Default behaviour is exactly the same as before, however `--ldap-base-dn` parameter now supports placeholder `{username}`. If the placeholder is found, the whole `--ldap-base-dn` is used as a DN.

Addresses issue https://github.com/shipyard/shipyard/issues/695

### CODE REVIEW

**Comment by ehazlett** [comment]
Since this can be anything perhaps it would be better as `{baseDN}` or something?

**Comment by meister** [comment]
The idea is that the placeholder is for the username variable that is used for authentication.
So for example: A user by the username `martin` logs in.
- When configured with `--ldap-base-dn="cn=users,cn=accounts,dc=company"` would produce LDAP dn `cn=martin,cn=users,cn=accounts,dc=company`
- When configured as `--ldap-base-dn="uid={username},cn=users,cn=accounts,dc=company"` would produce LDAP dn `uid=martin,cn=users,cn=accounts,dc=company`. `{username}` being the direct replacement from the login form (and variable used inside the method as well).

**Comment by ehazlett** [comment]
Hey sorry for the delay -- this needs a rebase.  Thanks!

**Comment by meister** [comment]
Branch should be now up to date with master. Removed excess files that were added previously.

**Comment by ehazlett** [comment]
lgtm

**Pull request merged**
