### PR TITLE
Dashboard operations

### PR DESCRIPTION
**Pull request by tombee**
Add a wrench icon that allows a user to stop/restart/destroy/scale containers and also to view log files.

As part of this I removed the clickable rows, since this was annoying and breaking copy/paste ability.

### CODE REVIEW

**Comment by ehazlett** [comment]
So I went to test this and there is an issue with bower :(  Apparently it can no longer find the `chartjs` dependency which means everything is broken.  I'm digging to see how to fix.

**Comment by ehazlett** [comment]
Looking good.  I think the icon should be a button to signal it does things.  Also, the scaling operation sometimes leaves the dim active and scale down doesn't appear to work.

**Comment by tombee** [comment]
@ehazlett 
I turned the icon into a button -- I'd done this originally but the default button is too big.. so since you insist :wink: I've changed it back to a button and reduced the padding.

I'm having a few issues with the 'scale' operation even on the container details screen (before this change).

**Comment by tombee** [comment]
Rebasing and re-testing this one now.

**Comment by tombee** [comment]
@ehazlett
I've rebased and re-tested this.

During the rebase I removed the 'scale' option from the dropdown (but only from the html).  I think this is a task in itself to work on that separately to improve the UX and error handling.

For now.. at least we have start, stop, restart and logs in the dashboard ops.

**Comment by ehazlett** [comment]
I'm closing this as we've addressed these in the new UI.  Thanks!

**Pull request closed without merging**
